[workspace]
members = [
	"bin/dnglab",
	"rawler",
	"embedftp"
]
resolver = "2"


[profile.bench]
debug = true
lto = "fat"

[profile.release]
opt-level = 3
overflow-checks = false
debug = 0
#lto = "fat"

